version: "3.8"

services:
  pg:
    image: postgres:14
    container_name: pg
    environment:
      - POSTGRES_USER=sokheng
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_micro

    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"